spring:
  application:
    name: domain-test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:realdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console